apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multi-platform-suite-component-zqus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multi-platform-suite-component-zqus
    app.kubernetes.io/part-of: multi-platform-suite-application-djhw
  name: multi-platform-suite-component-zqus
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: multi-platform-suite-component-zqus
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: multi-platform-suite-component-zqus
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-platform-build-tenant/multi-platform-suite-application-djhw/multi-platform-suite-component-zqus@sha256:18ae26c1d408667e2c1703988b784d090e3770c915d7746fc90ad888538ab9f0
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
